### ISSUE TITLE
Kernel build failure due to implicit function declaration

### ISSUE THREAD

**Issue by mstallmo** [InES-HPMM/linux-l4t-4.4-kernel#2]
Hi,

I have been attempting to build the Kernel for a Jetson TX2 based on the instructions in the Wiki but I keep running into build errors with `nvdec.c`. When building the `drivers/video` target running the `make Image` command I get the following error:

```
drivers/video/tegra/../../../../nvhost//drivers/video/tegra/host/nvdec/nvdec.c:361:2: error: implicit declaration of function ‘te_restore_keyslots’ [-Werror=implicit-function-declaration]
  te_restore_keyslots();
  ^
cc1: all warnings being treated as errors
```

I am building with Ubuntu 16.04 and the toolchain for L4T 28.2 

Thanks in advance for your help!

**Comment by mstallmo** [comment]
Update:: I removed the `-Wall` flag from the Makeffile and progressed further in the build but I am now running into another issue. There is a multiple definition error in `drivers/media/platform/tegra/camera/csi/csi.c`

```
drivers/media/built-in.o:(___ksymtab+tegra_get_mc_csi+0x0): multiple definition of `__ksymtab_tegra_get_mc_csi'
drivers/video/built-in.o:(___ksymtab+tegra_get_mc_csi+0x0): first defined here
drivers/media/built-in.o: In function `tegra_get_mc_csi':
/home/mason/linux-l4t-4.4/kernel/kernel-4.4/drivers/media/platform/tegra/camera/csi/csi.c:39: multiple definition of `tegra_get_mc_csi'
drivers/video/built-in.o:/home/mason/linux-l4t-4.4/kernel/kernel-4.4/drivers/video/tegra/../../../../nvhost//drivers/video/tegra/host/nvcsi/nvcsi.c:194: first defined here
scripts/Makefile.build:340: recipe for target 'drivers/built-in.o' failed
```

**Comment by dariis** [comment]
Did you do those steps: https://github.com/InES-HPMM/linux-l4t-4.4#building-the-kernel
On which branch are you working?
Did you choose the same branch for all sub repos?

**Comment by mstallmo** [comment]
I followed the steps from the Custom Kernel Compilation section of the Wiki here: https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation

I'm working on the l4t-r28.2.1 branch

I'm not 100% sure if I chose the same branch for the sub-repos. I'll double check that to be the case.

**Comment by mstallmo** [comment]
I just re-did my test from yesterday making sure that I was on the l4t-r28.2.1 branch for both the top level project and the sub-project. I am still getting the same implicit-function-declaration error.

To resolve this originally I had to make the following change:
* Remove the `-Werror-implicit-declaration` flag from the compiler options in the root Makefile in `kernel/kernel-4.4`.

After editing the above I had to make the following changes as well:
* Remove one of the instances of `tegra_get_mc_csi`. There is a re-definition error between `kernel-4.4/drivers/media/platform/tegra/camera/csi/csi.c` and `nvhost/drivers/video/tegra/host/nvcsi/nvcsi.c`

**Comment by dariis** [comment]
Sorry I can not reproduce your error.
You can check my terminal output:
[output.txt](https://github.com/InES-HPMM/linux-l4t-4.4-kernel/files/3260124/output.txt)

First make sure that all the sub repos are on the same branch. It is a little bit annoying because there are a lot of sub repos (due to the nvidia structure). In total there are 15 according to the `source_sync.sh` from nvidia:
```bash
# ...
SOURCE_INFO="
k:kernel/kernel-4.4:nv-tegra.nvidia.com/linux-4.4.git:
k:kernel/t18x:nv-tegra.nvidia.com/linux-t18x.git:
k:kernel/nvgpu:nv-tegra.nvidia.com/linux-nvgpu.git:
k:kernel/nvhost:nv-tegra.nvidia.com/linux-nvhost.git:
k:kernel/nvmap:nv-tegra.nvidia.com/linux-nvmap.git:
k:kernel/nvmap-t18x:nv-tegra.nvidia.com/linux-nvmap-t18x.git:
k:kernel/display:nv-tegra.nvidia.com/linux-display.git:
k:hardware/nvidia/soc/t18x:nv-tegra.nvidia.com/device/hardware/nvidia/soc/t18x.git:
k:hardware/nvidia/platform/tegra/common:nv-tegra.nvidia.com/device/hardware/nvidia/platform/tegra/common.git:
k:hardware/nvidia/platform/t18x/common:nv-tegra.nvidia.com/device/hardware/nvidia/platform/t18x/common.git:
k:hardware/nvidia/platform/t18x/quill:nv-tegra.nvidia.com/device/hardware/nvidia/platform/t18x/quill.git:
k:hardware/nvidia/soc/t210:nv-tegra.nvidia.com/device/hardware/nvidia/soc/t210.git:
k:hardware/nvidia/platform/t210/common:nv-tegra.nvidia.com/device/hardware/nvidia/platform/t210/common.git:
k:hardware/nvidia/platform/t210/jetson:nv-tegra.nvidia.com/device/hardware/nvidia/platform/t210/jetson.git:
k:hardware/nvidia/soc/tegra:nv-tegra.nvidia.com/device/hardware/nvidia/soc/tegra.git:
"
# ...
```

Did you install the recommended gcc toolchain 4.8.5:
https://developer.nvidia.com/embedded/dlc/l4t-gcc-toolchain-64-bit-28-2-ga
and then:
`export CROSS_COMPILE=<your_dir>/install/bin/aarch64-unknown-linux-gnu-`

**Comment by mstallmo** [comment]
Ahh yeah that seems to have done the trick. I didn't realize there were so many sub-repos that needed to be changed to the 28.2 branch before running the compile. 

Thank you so much for your help and patience!
